### ISSUE TITLE
Cannot install Rdpack

### ISSUE THREAD

**Issue by davebernie89** [GeoBosh/Rdpack#11]
I cannot install Rdpack, and am getting the following output 

> install.packages("Rdpack")
Installing package into ‘/home/d.bernstein/R/x86_64-redhat-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/Rdpack_0.11-1.tar.gz'
Content type 'unknown' length 693897 bytes (677 KB)
==================================================
downloaded 677 KB

* installing *source* package ‘Rdpack’ ...
** package ‘Rdpack’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package ‘Rdpack’
    finding HTML links ... done
    RStudio_reprompt                        html  
    Rd_combo                                html  
    Rdapply                                 html  
    Rdo2Rdf                                 html  
    Rdo_append_argument                     html  
    Rdo_collect_metadata                    html  
    Rdo_empty_sections                      html  
    Rdo_fetch                               html  
    Rdo_flatinsert                          html  
    Rdo_get_argument_names                  html  
    Rdo_get_insert_pos                      html  
    Rdo_get_item_labels                     html  
    Rdo_insert                              html  
    Rdo_insert_element                      html  
    Rdo_is_newline                          html  
    Rdo_locate                              html  
    Rdo_locate_leaves                       html  
    Rdo_macro                               html  
    Rdo_modify                              html  
    Rdo_modify_simple                       html  
    Rdo_piecetag                            html  
    Rdo_remove_srcref                       html  
    Rdo_reparse                             html  
    Rdo_sections                            html  
    Rdo_set_section                         html  
    Rdo_show                                html  
    Rdo_tag                                 html  
    Rdo_tags                                html  
    Rdo_which                               html  
    Rdpack-package                          html  

Error: argument is of length zero
* removing ‘/home/d.bernstein/R/x86_64-redhat-linux-gnu-library/3.3/Rdpack’
Warning in install.packages :
  installation of package ‘Rdpack’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp6RfIXR/downloaded_packages’

**Comment by GeoBosh** [comment]
Thanks for the report . 
Are you running R-3.3 on Red Hat? If you are installing the package using `install.packages`, could you run `sessionInfo()` and show the output here? 

I may have included something in the documentation that doesn't compile properly in R-3.3. Can you try to install without the html docs using:
```
install.packages("Rdpack", INSTALL_opts = c("--no-html"))
```
If that fails try installing without docs at all:
```
install.packages("Rdpack", INSTALL_opts = c("--no-docs"))
```
Let me know the result.

**Comment by davebernie89** [comment]
Hi Georgi,

I was running 3.4.3 and but updated to 3.6.2.  
Best,

David

www.davidharrybernstein.com

**Comment by GeoBosh** [comment]
Do you still have the problem?

**Comment by GeoBosh** [comment]
Do you still have the problem?

**Comment by davebernie89** [comment]
No 

Best,

David

www.davidharrybernstein.com
