### ISSUE TITLE
unhandled LaTeX sequence {\'i} -> í

### ISSUE THREAD

**Issue by MLopez-Ibanez** [GeoBosh/Rdpack#14]
```
@incollection{LopPaqStu09emaa,
  editor = { Thomas Bartz-Beielstein  and  Marco Chiarandini  and  Lu{\'i}s Paquete  and  Mike Preuss },
  year = 2010,
  address = {Berlin, Germany},
  publisher = {Springer},
  booktitle = {Experimental Methods for the Analysis of
                  Optimization Algorithms},
  author = { Manuel L{\'o}pez-Ib{\'a}{\~n}ez  and  Lu{\'i}s Paquete  and  Thomas St{\"u}tzle },
  title = {Exploratory Analysis of Stochastic Local Search
                  Algorithms in Biobjective Optimization},
  pages = {209--222},
  doi = {10.1007/978-3-642-02538-9_9},
 }
```
The above gets rendered as: 

Manuel López-Ibáñez, Lu\'is Paquete and Thomas Stützle (2010). “Exploratory Analysis of Stochastic Local Search Algorithms in Biobjective Optimization.” In Thomas Bartz-Beielstein, Marco Chiarandini, Lu\'is Paquete and Mike Preuss (eds.), Experimental Methods for the Analysis of Optimization Algorithms, pp. 209–222. Springer, Berlin, Germany. doi: 10.1007/978-3-642-02538-9_9.

**Comment by GeoBosh** [comment]
I am a little bit surprised that you got any diacritical marks since the diacritical marks are not preceded by backslashes., I suspect that you compiled this in a Spanish locale. Bear in mind that this is not portable. 

That said, I put backslashes in front of the diacritical marks and obtained what you showed in your comment. I am not completely sure what `'i ` is expected to do but since the dot in i needs to be dropped, I believe that the dot-less i will do. So, I replaced ` Lu{'i}s` with ` Lu{\'\i}s ` and it produced the accent above the i.

**Comment by MLopez-Ibanez** [comment]
> I am a little bit surprised that you got any diacritical marks since the diacritical marks are not preceded by backslashes. I suspect that you compiled this in a Spanish locale. Bear in mind that this is not portable.

No, it was not using the proper markdown markup here. Comment updated.

> That said, I put backslashes in front of the diacritical marks and obtained what you showed in your comment. I am not completely sure what `'i ` is expected to do but since the dot in i needs to be dropped, I believe that the dot-less i will do. So, I replaced ` Lu{'i}s` with `Lu{\'\i}s` and it produced the accent above the i.

I'll close this since you are right that is the proper way to write í (although pdfLaTeX seems quite lenient and produces the correct output with  `\'i`.

**Comment by MLopez-Ibanez** [comment]
Apologies, I thought about re-opening this because biblatex does not like `\'\i` See https://tex.stackexchange.com/questions/469555/unicode-u301-error-in-biblatex-but-not-in-main-text-i but I now think this is a problem in biblatex that hopefully will be solved some day.
