### ISSUE TITLE
genre unknown to bibConvert

### ISSUE THREAD

**Issue by kyoustat** [GeoBosh/Rdpack#17]
Hi Dr. Boshnakov,

After the recent update, newer builds with {devtools::build()} and {R CMD INSTALL} show the message that never appeared before

`genre {PhD} {Thesis} is currently unknown to bibConvert; using Misc instead`

I see no reason why such a parsing issue message occurs considering the REFERENCES.bib file has no item under item type of 'Thesis' at all.  As in your troubleshooting note, it still compiles and all the messages are appearing. However, due to that message that repeatedly appears, it's quite slowing down the entire build time. Thanks for your time in advance and as always I appreciate your efforts in building and developing this wonderful package.

**Comment by GeoBosh** [comment]
Hi Kisung,

Thanks for the report. This is probably a bug in `rbibutils`, I will fix it. It looks like some bib field is incorrectly changed to `Thesis`. 

If you get this behaviour in CRAN package(s), can you give name(s) of package(s) or example bib references?

Please don't hesitate to report any other issues that you encounter.

**Comment by kyoustat** [comment]
Two packages I've checked are **Rdimtools** and **Riemann**, both on CRAN.

**Comment by GeoBosh** [comment]
I made a change in the github repo of`rbibutils`(https://github.com/GeoBosh/rbibutils) which halved (or thereabout) the build time  for`Rdimtools`on my machine. I did some minor changes to Rdpack, but don't think they are relevant for this issue.

Can you check and let me know if the improvement is tangible. There is more to be done but I am very busy with teaching at the moment (blended learning and all that).

**Comment by GeoBosh** [comment]
I have now made some changes in `Rdpack` that lead to dramatic speed improvement of \insertRef processing. 
Not properly tested yet but on the packages that I tried there seem to be no adverse side effects. 

Bug reports are welcome, as usual.
