### ISSUE TITLE
doi entries should generate https links

### ISSUE THREAD

**Issue by MLopez-Ibanez** [GeoBosh/Rdpack#20]
Currently, the URLs generated by Rdpack for doi field are not https. This gives a message in CRAN:

 URL: http://doi.org/10.1007/3-540-44719-9_15 (moved to https://doi.org/10.1007/3-540-44719-9_15)
      From: man/eaf-package.Rd
      Status: 200
      Message: OK 

Although this message is harmless, it would be nice to directly generate https links.

**Comment by MLopez-Ibanez** [comment]
Very strange. I can see that the links are rendered correctly in HTML here:

https://mlopez-ibanez.github.io/eaf/reference/eaf-package.html

But the CRAN builder complains about the same links in the .Rd files:

https://win-builder.r-project.org/incoming_pretest/eaf_2.0_20210106_172059/Debian/00check.log

Well not a huge concern, but I wonder if I'm doing something wrong to trigger this behavior.

**Comment by MLopez-Ibanez** [comment]
i can trigger the same errors myself in r-hub: https://builder.r-hub.io/status/eaf_2.0.tar.gz-30839d61b47c4068a9f464fd89e5682e

That is using Rdpack 2.1.

**Comment by MLopez-Ibanez** [comment]
I also noticed that when I download the package built for Windows: https://artifacts.r-hub.io/eaf_2.0.tar.gz-30839d61b47c4068a9f464fd89e5682e

The URLs for the DOIs are wrong in the generated html pages, for example html/eaf-package.html : doi: <a href="http://doi.org/10.1007/3-540-44719-9_15">10.1007/3-540-44719-9_15</a>.

**Comment by GeoBosh** [comment]
Which version of R do you build `eaf` on?
Can you give me a link or send me the tarball of eaf? I actually need to look at `build/partial.rdb`.

**Comment by MLopez-Ibanez** [comment]
I believe this was due to an old version of R. I cannot reproduce it anymore with R 3.6.3. Thanks!
