### ISSUE TITLE
arXiv entry manipulation for manual url?

### ISSUE THREAD

**Issue by kyoustat** [GeoBosh/Rdpack#21]
Hi, I'm not sure whether this question is properly directed at Rdpack. In my `inst` file, I have a following entry
`@article{example,
	title = {A new method to simulate the {Bingham} and related distributions in directional data analysis with applications},
	journal = {arXiv:1310.8110 [math, stat]},
	author = {Kent, John T. and Ganeiber, Asaad M. and Mardia, Kanti V.},
	month = oct,
	year = {2013},
	note = {arXiv: 1310.8110},
}`
and Rdpack generates the following entry in my Rd file
`Kent JT, Ganeiber AM, Mardia KV (2013). “A new method to simulate the Bingham and related distributions in directional data analysis with applications.” arXiv:1310.8110 [math, stat]. 1310.8110, http://arxiv.org/abs/1310.8110.`. 

When submitting a package to CRAN, however, this is accepted as a *note* with a message that arxiv entry needs to be accompanied with **https**, not **http**. So I was wondering if this can be handled at Rdpack level to give a manual url.

**Comment by GeoBosh** [comment]
Thanks for the report. 

I think that the problem comes from `rbibutils` but since that package is also mine, I will fix it. There is no need to report there.

**Comment by GeoBosh** [comment]
I have now fixed this in `rbibutils`. Thanks for reporting it and the nice example.

I need to check all reverse dependencies of `Rdpack`, which needs some time, before updating `rbibutils` on CRAN.

But you don't need to wait for `rbibutils` to be updated on CRAN. Just install it from Github and build your package with it. Feel free to reopen the issue if problems occur.

**Comment by kyoustat** [comment]
Thanks for your update! Also, I had some cases where the CRAN check process
was not able to fetch the url's written in Rd files. This scenario was
another reason to ask for an option to remove certain bib fields in general.

**Comment by GeoBosh** [comment]
You can file a request for this, with more specifics. It is not a problem to add further macros but if a URL is not reliable it may be better to remove it from the bib file. On the other hand, if it is glitch that cran can't  access it, it is probably not your problem. But I may be missing something, requests for improvement are welcome.
