### ISSUE TITLE
Cryptic error message when calling the RStudio addin with no file open in the editor

### ISSUE THREAD

**Issue by daattali** [GeoBosh/Rdpack#30]
If no file is open in the editor, an error is shown

![image](https://user-images.githubusercontent.com/952340/206754286-a3c50988-a424-4227-aa6f-e1815b761250.png)

Instead it should be more clear that a file is expected to be open. I didn't know what this addin is, I tried clicking it, and got this random error.

**Comment by GeoBosh** [comment]
Thanks for the report.

You are right. The message The message is confusing and should be fixed with something more suitable.

**Comment by GeoBosh** [comment]
Fixed now. The error message now mentions the help page of the underlying function.
