### ISSUE TITLE
Lost Braces issue on Ubuntu-latest (devel) on GH

### ISSUE THREAD

**Issue by mikeroswell** [GeoBosh/Rdpack#32]
It looks like this issue has been partly solved before:
https://stat.ethz.ch/pipermail/r-devel/2023-November/083007.html
But I'm getting checkRd errors on Ubuntu-latest (devel) only, when using GH actions: https://github.com/mikeroswell/MeanRarity/actions/runs/7200026411/job/19613024879
Thanks!

**Comment by GeoBosh** [comment]
Thanks for the report, though in this case the error is from elsewhere in your documentation.

The NOTEs below are not from Rdpack, they come from your roxygen documentation. You need  to remove one of the backslashes in `\\verb{` in each case. A double backslash prints verbatim and then the braces remain superfluous. If you just have `\verb`  then the braces delimit the argument to that . The Rd files are generated by roxygen but you should be able to figure out the R file from which they come.
```
checking Rd files ... NOTE
  checkRd: (-1) beeAbunds.Rd:11: Lost braces
      11 | \item \emph{\\verb{Cold Soil_5\\}}: number of records of given species from site "Cold
         |                   ^
  checkRd: (-1) beeAbunds.Rd:13: Lost braces
      13 | \item \emph{\\verb{Fox Hill_5\\}}: number of records of given species from site "Fox Hill"
         |                   ^
  checkRd: (-1) beeAbunds.Rd:15: Lost braces
      15 | \item \emph{\\verb{IAS_3\\}}: number of records of given species from site "IAS" during 
```
Rdpack would be the culprit if the NOTEs are in references generated by `\insertRef` and similar macros from Rdpack.:)
