### ISSUE TITLE
Question about R help page

### ISSUE THREAD

**Issue by yayayaoyaoyao** [GeoBosh/Rdpack#34]
Thank you for the nice package. I am trying to follow the same steps on GitHub. However, the references I generated on the R help page are different. Do you know why?  
<img width="315" alt="Capture" src="https://github.com/GeoBosh/Rdpack/assets/75678975/aef47486-3820-408c-909b-a138137177c2">

The reference part shows \Sexpr[results=rd,stage=build]{Rdpack::insert_ref(key=" xxx",package="xxx")} not the reference format I expected.

**Comment by GeoBosh** [comment]
I could make a guess or guesses what is wrong. But if you show here what you put in your documentation file (roxygen2 comments if you use them, or the Rd chunk otherwise), I will tell you exactly what is wrong.:)

Even better, put your package on github and I will look it up there,

**Comment by yayayaoyaoyao** [comment]
Thank you for the reply. My R package isn't ready yet. I'm currently working on inserting references. I noticed that some people simply type in the references, while others find Rdpack helpful. However, I've encountered an issue where Rdpack doesn't display the references. I follow exactly the same thing as below.  My REFERENCES.bib is like what you have in the inst folder. When I call the reference in R help page, I just use @references \insertRef{xxx}{xxx}, it returns the screenshot. Do you have any suggestions? 

Add the following lines to file "DESCRIPTION":

Imports: Rdpack
RdMacros: Rdpack
Make sure the capitalisation of RdMacros: is as shown. If the field RdMacros: is already present, add "Rdpack" to the list on that line. Similarly for field "Imports:".

Add the following line to file "NAMESPACE":

importFrom(Rdpack,reprompt)
The equivalent line for roxygen2 is

#' @importFrom Rdpack reprompt
Create file REFERENCES.bib in subdirectory inst/ of your package and put the BibTeX references in it.

**Comment by GeoBosh** [comment]
Indeed, more than 400 packages on github and Bioconductor use Rdpack for this purpose. 

The second argument to the macro should be the name of your package:
```
 @references \insertRef{xxx}{name_of_your_package}
```
Please, let me know if this solves the issue. 

By the way, it doesn't matter that your package is unfinished. It is very useful to commit and push while you work, at the very least this is a bulletproof backup.

**Comment by yayayaoyaoyao** [comment]
No, it does not slove the issue. @references \insertRef{xxx}{name_of_your_package} gives the results of screen shoot.

**Comment by yayayaoyaoyao** [comment]
Do you know some packages use Rdpack ? Maybe I can check against it.

**Comment by yayayaoyaoyao** [comment]
There is no message when I build the package.
Yes, I am trying to just render the page inside R studio.
The screenshot is exactly what happened after I install the package, load it with the library and use the ?xxx.

**Comment by GeoBosh** [comment]
As I said before, If I don't know exactly what is going on, I can only guess. It is so easy to to put the package to github or send me a link to the source somewhere else.

**Comment by yayayaoyaoyao** [comment]
I just checked Rdpack::viewRd shows the result correctly. But not in Rstudio when I use ?xxx, do you know why?

**Comment by GeoBosh** [comment]
>  just checked Rdpack::viewRd shows the result correctly. But not in Rstudio when I use ?xxx, do you know why?

I think that RStudio fixed this several years ago, so it should render it correctly if you have reasonably recent version of RStudio.
Do you use library() or devtools::load_all()? If the former, it might be a regression in RStudio?

**Comment by yayayaoyaoyao** [comment]
I think the issue is I updated something in the package and I am running the check for the package. at the same time, the old package gives this issue. After the check is done, I reinstall the package, it works. Thanks.
