### ISSUE TITLE
Reference Section Blank in pkgdown 2.1.1 for Built Websites

### ISSUE THREAD

**Issue by Carol-seven** [GeoBosh/Rdpack#36]
Hi Dr. Boshnakov,

Thank you for your nice package, which has been very useful in creating my R packages. However, I encountered an issue when using the pkgdown package.

When I build the website for my own R package (`@references \insertAllCited{}`), I noticed that the "Reference" section appears blank. The code I used is: `devtools::build_site()`.

This worked in the past, so I double-checked the cause. It seems that the issue arose after updating pkgdown from version 2.1.0 to 2.1.1. When I removed the latest version and reinstalled 2.1.0, the "Reference" section displayed correctly.

Any insights or recommendations would be greatly appreciated. Thanks again for your work on this package.

**Comment by GeoBosh** [comment]
Thanks for the report and the good words about Repack.

There is a bug in v2.1.1 of pkgdown - they accidentally stopped loading Rd macros when processing documentation. The bug is fixed on GitHub. So you can either install pkgdown from GitHub or revert to 2.1.0.
