### ISSUE TITLE
Force intext citations to be et al when >3 authors

### ISSUE THREAD

**Issue by tpbilton** [GeoBosh/Rdpack#6]
I have an R package called [GUSMap](https://github.com/tpbilton/GUSMap) that I have been developing and I have starting using Rdpack for managing my references. However, I'm finding that the first time I cite a reference, all the authors are displayed (this happens in this [file](https://github.com/tpbilton/GUSMap/blob/master/R/GUSMap-package.R)). Can Rdpack be forced to convert intext citations to et al when there are more than 3 authors?

Thanks.

**Comment by GeoBosh** [comment]
Thanks for the report and the example. This needs fixing, I will look into it.

**Comment by tpbilton** [comment]
Thanks, I'll have a look at this tomorrow.

Re the rendering of the fourth author. Yes I have noticed this as will. I had thought this could be due to the fact that I generated the  rd files on linux using roxgyen2 because the bug only seems to show when I install on Windows. I haven't really had time to look more into it though.

**Comment by GeoBosh** [comment]
Indeed, I am currently on my Windows machine and thought that this might have something to do with the problem. Are you saying that on linux it's ok?

**Comment by tpbilton** [comment]
Right, I've had a look at and yes your fix has done the trick, thank you.

Re the rendering issues: Yes it is fine on linux. I tried running roxygenise on Windows it didn't change anything. So, it seems that there is some issue with rendering special characters in Windows? Could it be an encoding issue?

**Comment by GeoBosh** [comment]
Yes, it is an encoding issue. Roxygen indeed is not relevant here.

 I am pretty sure that the issue is in `\Sexpr`. I will report it on R-devel but  writing a minimal example for encoding related issues needs some care and I am marking an exam at the moment. It's good that the issue is only on Windows.
